---

- hosts: meraki_servers
  vars:
    organization_id: 12345678901234567890
  gather_facts: false
  tasks:

    - name: Get all organization's devices statuses
      cisco.meraki.organizations_devices_statuses_info:
        organizationId: "{{ organization_id }}"
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"
