---
- hosts: meraki_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get all Organizations
      cisco.meraki.organizations_info:
        meraki_api_key: "{{meraki_api_key}}"
        # meraki_username: "{{meraki_username}}"
        # meraki_password: "{{meraki_password}}"
        # meraki_verify: "{{meraki_verify}}"
        # meraki_port: "{{meraki_port}}"
        # meraki_version: "{{meraki_version}}"
        # meraki_debug: "{{meraki_debug}}"
        # headers: "{{my_headers | from_json}}"
        organizationId: "575334852396583071"
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"
