---
- hosts: meraki_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Create
      cisco.meraki.organizations_saml_idps:
        meraki_api_key: "{{meraki_api_key}}"
        state: present
        organizationId: "828099381482762270"
        sloLogoutUrl: https://somewhere.com
        x509certSha1Fingerprint: 00:11:22:33:44:55:66:77:88:99:00:11:22:33:44:55:66:77:88:99
