---

- hosts: meraki_servers
  vars:
    org_id: "828099381482762270"
    corp_name: "TEST 2"
    network_id: "L_828099381482770865"
  gather_facts: false
  tasks:

    - name: Create corporate SSID
      cisco.meraki.networks_wireless_ssids:
        meraki_suppress_logging: false
        state: present
        enabled: true
        name: "{{corp_name}}"
        networkId: "{{ network_id }}"
        number: 0
        authMode: "8021x-radius"
        radiusServers: 
          - one:
            host: "1.2.3.4"
            port: 1812
            secret: SuperSecretPassword
          - one:
            host: "1.2.3.5"
            port: 1818
            secret: SuperSecretPassword
          