---

- hosts: localhost
  vars:
    network_id: "L_828099381482771185" # Branch-1234
  gather_facts: false
  tasks:

    - name: Update appliance Vlans
      cisco.meraki.networks_appliance_vlans:
        state: present
        applianceIp: 192.168.1.2
        cidr: 192.168.1.0/24
        id: '1234'
        name: My VLAN
        networkId: "{{network_id}}"
        subnet: 192.168.1.0/24

    - name: Get all networks _appliance _ssids
      cisco.meraki.networks_appliance_ssids_info:
        networkId: "{{network_id}}"
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Update appliance SSID
      cisco.meraki.networks_appliance_ssids:
        state: present
        authMode: 8021x-radius
        defaultVlanId: 10
        enabled: true
        name: My SSID
        networkId: "{{network_id}}"
        number: 1
        radiusServers:
        - host: 1.2.3.4
          port: 1000
          secret: secret
        visible: true
        wpaEncryptionMode: WPA2 only 


# ################################################################

    - name: Update appliance traffic sharping
      cisco.meraki.networks_appliance_traffic_shaping:
        state: present
        globalBandwidthLimits:
          limitDown: 5120
          limitUp: 2048
        networkId: "{{network_id}}"

    - name: Enable Vlans on the MX
      cisco.meraki.networks_appliance_vlans_settings:
        state: present
        networkId: "{{network_id}}"
        vlansEnabled: true

    # - name: Update appliance ports
    #   cisco.meraki.networks_appliance_ports:
    #     accessPolicy: "open"
    #     allowedVlans: "all"
    #     enabled: true
    #     networkId: "{{network_id}}"
    #     portId: "2"
    #     type: "trunk"
    #     vlan: 10
    #     state: present
          